# Usage:
# make        # compile all binary
# make clean  # remove ALL binaries and objects
CC=gcc
CFLAGS=-g -Wall
TARGET=spies

spiesmake:
	$(CC) $(FLAGS) -o $(TARGET) $(TARGET).c 

clean:
	@echo "Cleaning up..."
	rm $(TARGET)