require "rake/testtask"

Rake::TestTask.new :pass do |task|
task.pattern = "test/pass/*_minitest.rb"
task.warning = false 
end

Rake::TestTask.new :errors do |task|
task.pattern = "test/errors/*_minitest.rb"
task.warning = false 
end
